name: flutter_ble_peripheral_example
description: Demonstrates how to use the flutter_ble_peripheral plugin.
publish_to: 'none'

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ble_peripheral:
    path: ../flutter_ble_peripheral/
  flutter_blue_plus: ^1.33.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  uses-material-design: true
